version: '3'

networks: 
  docker-jenkins_default:
    external: true

services:
  selenium-hub:
    image: selenium/hub
    ports:
      - 4444:4444
    networks: 
      - docker-jenkins_default

  firefox-node:
    image: selenium/node-firefox-debug
    ports:
      - 25901:5900
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_HOST: selenium-hub
      HUB_PORT: 4444
      NODE_MAX_INSTANCES: 1
      NODE_MAX_SESSION: 1
    networks: 
      - docker-jenkins_default

  firefox-node-1:
    image: selenium/node-firefox-debug
    ports:
      - 25902:5900
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_HOST: selenium-hub
      HUB_PORT: 4444
      NODE_MAX_INSTANCES: 1
      NODE_MAX_SESSION: 1
    networks: 
      - docker-jenkins_default

  firefox-node-2:
    image: selenium/node-firefox-debug
    ports:
      - 25903:5900
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_HOST: selenium-hub
      HUB_PORT: 4444
      NODE_MAX_INSTANCES: 1
      NODE_MAX_SESSION: 1
    networks: 
      - docker-jenkins_default

  chrome-node:
    image: selenium/node-chrome-debug
    ports:
      - 25910:5900
    depends_on:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_HOST: selenium-hub
      HUB_PORT: 4444
      NODE_MAX_INSTANCES: 1
      NODE_MAX_SESSION: 1
    networks: 
      - docker-jenkins_default
